openapi: 3.0.3
info:
  title: Hotel Booking
  description: Simple example of hotel booking app
  version: 1.0.0

paths:
  /api/auth/v1/session:
    post:
      operationId: logIn
      summary: Log in using credentials
      description: |
        Log in with username/password. Successful authentication will result in a "SessionId" cookie being set
      tags:
        - auth
        - session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - login_id
                - password
              properties:
                login_id:
                  type: string
                password:
                  description: User password; secret
                  type: string
      responses:
        "201":
          description: Authentication successful & session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
          headers:
            Set-Cookie:
              schema:
                type: string
                format: cookie
        "401":
          description: Invalid credentials provided
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemResponse'


    get:
      operationId: fetchAuthState
      summary: Get current authentication state
      security:
        - session: [ ]
      tags:
        - auth
        - session
      responses:
        "200":
          description: Return details of currently authenticated session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        "401":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemResponse'

  /api/auth/v1/session/anonymous:
    post:
      operationId: createAnonymousSession
      summary: Create anonymous user & a session for the new user
      tags:
        - auth
        - session
      responses:
        "201":
          description: Return details of newly created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
          headers:
            Set-Cookie:
              schema:
                type: string
                format: cookie

  /api/auth/v1/user:
    post:
      operationId: signUp
      summary: Sign up as a new customer & create a session for the new user
      description: |
        Session credentials are optional for this endpoint. If called with credentials of an anonymous user,
        the sign-in credentials will be stored against the anonymous user ID & that user will no longer be anonymous.
      security:
        - session: [ ]
      tags:
        - auth
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - login_id
                - password
                - name
              properties:
                login_id:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        "201":
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
          headers:
            Set-Cookie:
              schema:
                type: string
                format: cookie
        "409":
          description: |
            Username is not available
            This code will also be sent if supplied session is associated with a non-anonymous user
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemResponse'


components:
  securitySchemes:
    session:
      type: apiKey
      in: cookie
      name: SessionId

  schemas:
    SessionResponse:
      type: object
      required:
        - user_id
        - user_roles
        - anonymous_user
        - session_expiry_time
      properties:
        user_id:
          type: string
        login_id:
          type: string
        user_roles:
          type: array
          items:
            type: string
        anonymous_user:
          type: boolean
        session_expiry_time:
          type: string
          format: date-time

    ProblemResponse:
      type: object
      required:
        - title
        - code
        - status
        - detail
        - instance
      properties:
        title:
          type: string
        code:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
        extendedDetails:
          type: array
          items:
            type: object
            required:
              - code
              - detail
            properties:
              code:
                type: string
              detail:
                type: string
