version: '3.8'
services:
  postgresql:
    image: 'postgres:13.11-bullseye'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=${DB_NAME}'
